//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import Foundation

let start = CFAbsoluteTimeGetCurrent()

var n0 = 1
var n1 = 1
var sum = 0
while n1 < 4000000 {
    let new = n0 + n1
    n0 = n1
    n1 = new
    sum += new % 2 == 0 ? new : 0
}
print(sum)

let diff = CFAbsoluteTimeGetCurrent() - start
print("\(#function) Took \(diff) seconds")


